services:
  - type: web
    name: taskextreme-ai-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GITHUB_TOKEN
        sync: false
    healthCheckPath: /health 